name: reviewdog
on: [pull_request]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Detecting secrets
      uses: karankohli13/action-detect-secrets@master
      with:
        reporter: github-check
        github_token: ${{ secrets.github_token }} 
        fail_on_error: true
        detect_secrets_flags: --exclude-files .git
        slack_token: ${{ secrets.slack_token }}
        git_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}